before:
  hooks:
    - go mod tidy

builds:
  - id: b-build
    main: ./cmd/b/main.go
    binary: b
    ldflags:
      - -w
      - -X {{ .ModulePath }}/cmd/b.version={{ .Version }}
      - -X {{ .ModulePath }}/cmd/b.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: all
    signature: ${artifact}.sig
    id: b-sign
    ids:
      - b-build
    args:
      - --batch
      - --local-user=fentas@github.com
      - --pinentry-mode=loopback
      - --output=${signature}
      - --detach-sign
      - ${artifact}

archives:
  - id: b-archive
    builds:
      - b-build
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md

dockers:
  - id: amd64
    image_templates:
      - "ghcr.io/fentas/b:{{ .Version }}-amd64"
      - "ghcr.io/fentas/b:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goarch: amd64
  - id: arm64
    image_templates:
      - "ghcr.io/fentas/b:{{ .Version }}-arm64"
      - "ghcr.io/fentas/b:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/fentas/b:{{ .Version }}"
    image_templates:
      - "ghcr.io/fentas/b:{{ .Version }}-amd64"
      - "ghcr.io/fentas/b:{{ .Version }}-arm64"
  - name_template: "ghcr.io/fentas/b:latest"
    image_templates:
      - "ghcr.io/fentas/b:latest-amd64"
      - "ghcr.io/fentas/b:latest-arm64"

release:
  draft: false
  extra_files:
    - glob: install.sh
